version: "3.9"
services:
  hummingbot:
    container_name: hummingbot
    # Uncomment `build` for local builds and comment out the `image` line
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./conf:/home/hummingbot/conf
      - ./conf/connectors:/home/hummingbot/conf/connectors
      - ./conf/strategies:/home/hummingbot/conf/strategies
      - ./conf/controllers:/home/hummingbot/conf/controllers
      - ./conf/scripts:/home/hummingbot/conf/scripts
      - ./logs:/home/hummingbot/logs
      - ./data:/home/hummingbot/data
      - ./certs:/home/hummingbot/certs
      - ./scripts:/home/hummingbot/scripts
      - ./controllers:/home/hummingbot/controllers
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    tty: true
    stdin_open: true
    network_mode: host
    environment:
      - CONFIG_PASSWORD=p71!ggez1nJgJ@Zs
      - CONFIG_FILE_NAME=custom_volume_pumper.py
    #    - SCRIPT_CONFIG=conf_simple_pmm_example.yaml

  # gateway:
  #  container_name: gateway
  #  image: hummingbot/gateway:latest
  #  ports:
  #    - "15888:15888"
  #    - "8080:8080"
  #  volumes:
  #    - "./gateway_files/conf:/home/gateway/conf"
  #    - "./gateway_files/logs:/home/gateway/logs"
  #    - "./gateway_files/db:/home/gateway/db"
  #    - "./certs:/home/gateway/certs"
  #  environment:
  #    - GATEWAY_PASSPHRASE=a
